portfolio/config/routes.rb
Rails.application.routes.draw do
  get 'about_me/index'
  get 'about_me/edit'
  get 'about_me/update'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  
  get '/', to: 'home#index' 
  get '/about', to: 'home#about' 

 
  resources :projects
  resources :skills
  resources :contacts
  resources :user

  namespace :admin do 
    resources :projects
    resources :skills
    resources :about_me
  end
 

#admins-----
  get 'admin/about_me'
  get 'admin/skills'
  get 'admin/projects'

end

portfolio/app/models/about_me.rb
class AboutMe < ApplicationRecord
end

portfolio/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

portfolio/app/models/contact.rb
class Contact < MailForm::Base
    attribute :name, validate: true
    attribute :message


    def headers
    {
        subject: 'PROBANDO',
        to: 'edwardT_223@hotmail.com',
        from: %(#{name} <#{'edwardT_223@hotmail.com'}>)
    }
    end
end

portfolio/app/models/project.rb
class Project < ApplicationRecord
    has_many :project_technologies, class_name: 'ProjectTechnology'
    has_many :technologies, through: :project_technologies
end

portfolio/app/models/project_tecnology.rb
class ProjectTecnology < ApplicationRecord
    belongs_to :project
    belongs_to :technology
end

portfolio/app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
  
end

portfolio/app/models/skill.rb
class Skill < ApplicationRecord
end

portfolio/app/models/skill_type.rb
class SkillType < ApplicationRecord
end

portfolio/app/models/social_medium.rb
class SocialMedium < ApplicationRecord
end

portfolio/app/models/tecnology.rb
class Tecnology < ApplicationRecord
    has_many :project_technologies
    has_many :technologies, through: :project_technologies
end

portfolio/app/models/user.rb
class User < ApplicationRecord
  rolify
  
    
  

  # enum role: [:regular, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

portfolio/app/models/user_skill.rb
class UserSkill < ApplicationRecord
end

portfolio/app/controllers/admin/skills_controller.rb
class Admin::SkillsController < ApplicationController
    # def index
    #     @skills = Skill.all
    #     render index:
    # end

    def new
        @skill = Skill.new
    end 

    def create
        @skill = Skill.new(skill_params)
        if @skill.save
     
          redirect_to '/admin/skills'
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit
        @skill = Skill.find(params[:id])
    end

    def update
        @skill = Skill.find(params[:id])
        if @skill.update(skill_params)
   
          redirect_to '/admin/skills'
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @skill = Skill.find(params[:id])
        @skill.destroy
        flash[:notice] = "Skill deleted"
        redirect_to admin_skills_path
    end

      private 
      def skill_params
        params.require(:skill).permit( :Description, :Skill_type_id)
      end
end

portfolio/app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def about
        render :about
    end

    def skills
        render :skills
    end

    def projects
        render :projects
    end

end

portfolio/app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    def index
        render :index
    end

    def about
        @user = User.find(1)
        render :about
        
    end
end

portfolio/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    def index
        render :index
    end
end

portfolio/app/controllers/user_controller.rb
class UserController < ApplicationController
    include Rolify
    def index

        @user = User.find(1)
        @user.add_role :admin
        render :index
        authorize @user
        
    end
end

portfolio/app/helpers/about_me_helper.rb
module AboutMeHelper
end

portfolio/app/helpers/admin_helper.rb
module AdminHelper
end

portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

portfolio/app/helpers/contact_helper.rb
module ContactHelper
end

portfolio/app/helpers/home_helper.rb
module HomeHelper
end

portfolio/app/helpers/projects_helper.rb
module ProjectsHelper
end

portfolio/app/helpers/skills_helper.rb
module SkillsHelper
end

portfolio/app/helpers/user_helper.rb
module UserHelper
end

portfolio/app/views/admin/skills/index.html.erb
<%= render "layouts/header", home: @home %>

<% Skill.all.each do |skill| %>
 <h3><%= skill.Description   %></h3>

 
 <!-- Add a link to the edit action -->
 <%= link_to 'Edit', edit_admin_skill_path(skill), class: 'btn btn-primary' %>
 
 <!-- Add a link to the delete action -->
 <%= link_to 'Delete', admin_skill_path(skill), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
 
<hr>
<% end %>


<%= link_to "Nuevo", new_admin_skill_path %>

<%= render "layouts/footer", home: @home %>

portfolio/app/views/admin/skills/new.html.erb
<%= render "layouts/header", home: @home %>

<h2>Create new skill:</h2>

<%= form_for @skill, url: admin_skills_path do |f| %>
<br>
    <div class="field">
        <%= f.label :Description %>
<br>
        <%= f.text_area :Description %>
    </div>
    <div class="field">
    <br>
        <%= f.label :Skill_type_id %>
<br>
        <%= f.collection_select :Skill_type_id, SkillType.all, :id, :Description, prompt: "Tipo de habilidad" %>
    </div>
<br>
    <!-- Otros campos del formulario -->
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>
<%= render "layouts/footer", home: @home %>

portfolio/app/views/skills/index.html.erb
<%= render "layouts/header", home: @home %>
<% Skill.all.each do |skill| %>
 <h3><%= skill.Description   %></h3>
<% end %>
<%= render "layouts/footer", home: @home %>