portfolio/config/routes.rb
Rails.application.routes.draw do
  get 'about_me/index'
  get 'about_me/edit'
  get 'about_me/update'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  
  get '/', to: 'home#index' 
  get '/about', to: 'home#about' 

 
  resources :projects
  resources :skills
  resources :contacts
  resources :user

  namespace :admin do 
    resources :projects
    resources :skills
    resources :about_me
  end
 

#admins-----
  get 'admin/about_me'
  get 'admin/skills'
  get 'admin/projects'

end

portfolio/app/models/about_me.rb
class AboutMe < ApplicationRecord
end

portfolio/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

portfolio/app/models/contact.rb
class Contact < MailForm::Base
    attribute :name, validate: true
    attribute :message


    def headers
    {
        subject: 'PROBANDO',
        to: 'edwardT_223@hotmail.com',
        from: %(#{name} <#{'edwardT_223@hotmail.com'}>)
    }
    end
end

portfolio/app/models/project.rb
class Project < ApplicationRecord
    has_many :project_technologies, class_name: 'ProjectTechnology'
    has_many :technologies, through: :project_technologies
end

portfolio/app/models/project_tecnology.rb
class ProjectTecnology < ApplicationRecord
    belongs_to :project
    belongs_to :technology
end

portfolio/app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
  
end

portfolio/app/models/skill.rb
class Skill < ApplicationRecord
end

portfolio/app/models/skill_type.rb
class SkillType < ApplicationRecord
end

portfolio/app/models/social_medium.rb
class SocialMedium < ApplicationRecord
end

portfolio/app/models/tecnology.rb
class Tecnology < ApplicationRecord
    has_many :project_technologies
    has_many :technologies, through: :project_technologies
end

portfolio/app/models/user.rb
class User < ApplicationRecord
  rolify
  
    
  

  # enum role: [:regular, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

portfolio/app/models/user_skill.rb
class UserSkill < ApplicationRecord
end

portfolio/app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
    def index
        @projects = Project.all
    end

    def show
        @project = Project.find(params[:id])
    end

    def edit
        @project = Project.find(params[:id])
        @tecnologies = Tecnology.all
    end

    def update
        @project = Project.find(params[:id])
    
        if @project.update(project_params)
          redirect_to '/admin/projects'
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def new
        @project = Project.new
        @tecnologies = Tecnology.all
    end
    
    
    def create
        @project = Project.new(project_params)
    
        if @project.save
         
          
          redirect_to admin_projects_path

        end
    end

    def destroy
        @project = Project.find(params[:id])
        @project.destroy
        redirect_to '/admin/projects'
    end
    
    private 
    
      def project_params
        params.require(:project).permit(:name, :description, :responsabilities, :start_date, :finish_date, :user_id, :tecnologies_id)
      end
end

portfolio/app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    def index
        render :index
    end

    def about
        @user = User.find(1)
        render :about
        
    end
end

portfolio/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
        render :index
    end
    def show
        @project = Project.find(params[:id])
       end

end

portfolio/app/controllers/user_controller.rb
class UserController < ApplicationController
    include Rolify
    def index

        @user = User.find(1)
        @user.add_role :admin
        render :index
        authorize @user
        
    end
end

portfolio/app/helpers/about_me_helper.rb
module AboutMeHelper
end

portfolio/app/helpers/admin_helper.rb
module AdminHelper
end

portfolio/app/helpers/application_helper.rb
module ApplicationHelper
end

portfolio/app/helpers/contact_helper.rb
module ContactHelper
end

portfolio/app/helpers/home_helper.rb
module HomeHelper
end

portfolio/app/helpers/projects_helper.rb
module ProjectsHelper
end

portfolio/app/helpers/skills_helper.rb
module SkillsHelper
end

portfolio/app/helpers/user_helper.rb
module UserHelper
end

portfolio/app/views/admin/projects/edit.html.erb
<%= render "layouts/header", home: @home %>
<%= form_with(model: @project, url: admin_project_path(@project), local: true, method: :patch) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :responsabilities %>
    <%= f.text_area :responsabilities %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :finish_date %>
    <%= f.date_field :finish_date %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= render "layouts/footer", home: @home %>

portfolio/app/views/admin/projects/index.html.erb
<%= render "layouts/header", home: @home %>
<ul class="list_name">
    <% Project.all.each do |projects| %>
         
        <li>
           <h1> <%= link_to projects.name, admin_project_path(projects), method: :get %></h1>
        <li>
        
    <% end %>
<ul>
<%= link_to "New project", new_admin_project_path %>

<%= render "layouts/footer", home: @home %>

portfolio/app/views/admin/projects/new.html.erb
<%= render "layouts/header", home: @home %>
<%= form_with(model: @project, url: admin_projects_path, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.fields_for :project_technologies do |pt| %>
    
  <div class="field">
    <%= pt.label :tecnologies_id, 'Tecnologías' %>
    <%= pt.collection_select :tecnologies_id, @tecnologies, :id, :name, multiple: true,  :prompt => 'Choose a technology' %>
    <%= pt.collection_select :tecnologies_id, @tecnologies, :id, :name, multiple: true,  :prompt => 'Choose a technology' %>
    <%= pt.collection_select :tecnologies_id, @tecnologies, :id, :name, multiple: true,  :prompt => 'Choose a technology' %>
    <br>
    <%= pt.collection_select :tecnologies_id, @tecnologies, :id, :name, multiple: true,  :prompt => 'Choose a technology' %>
    <%= pt.collection_select :tecnologies_id, @tecnologies, :id, :name, multiple: true,  :prompt => 'Choose a technology' %>
  </div>
  <% end %>

  
  <div class="field">
    <%= f.label :responsabilities %>
    <%= f.text_area :responsabilities %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_field :start_date %>
  </div>

  <div class="field">
    <%= f.label :finish_date %>
    <%= f.date_field :finish_date %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit :project_technologies %>
  </div>
<% end %>

<%= render "layouts/footer", home: @home %>

portfolio/app/views/admin/projects/show.html.erb
<%= render "layouts/header", home: @home %>
<strong>Name:</strong> <%= @project.name %><br>
<strong>Description:</strong> <%= @project.description %><br>
<strong>Responsabilities:</strong> <%= @project.responsabilities %><br>
<strong>Start Date:</strong> <%= @project.start_date %><br>
<strong>Finish Date:</strong> <%= @project.finish_date %>
<br>
<%= link_to "Edit", edit_admin_project_path(@project) %>
<li>
  <%= link_to "Destroy", admin_project_path(@project), data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
</li>
<%= link_to 'Volver', admin_projects_path %>
<%= render "layouts/footer", home: @home %>

portfolio/app/views/projects/index.html.erb
<%= render "layouts/header", home: @home %>
<ul class="list_name">
    <% Project.all.each do |projects| %>
         
        <li>
           <h1> <%= link_to projects.name, project_path(projects), method: :get %></h1>
        <li>
        
    <% end %>
<ul>
<%= render "layouts/footer", home: @home %>

portfolio/app/views/projects/show.html.erb
<%= render "layouts/header", home: @home %>
      <strong>Name:</strong> <%= @project.name %><br>
      <strong>Description:</strong> <%= @project.description %><br>
      <strong>Responsibilities:</strong> <%= @project.responsabilities %><br>
      <strong>Start Date:</strong> <%= @project.start_date %><br>
      <strong>Finish Date:</strong> <%= @project.finish_date %>
    
    <%= link_to 'Volver', projects_path %>
<%= render "layouts/footer", home: @home %>